# Welcome to Shakespeare play classification

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [18]:
df = pd.read_csv(Path("data/Shakespeare_data.csv"))

In [19]:
df.head()

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"

## We can see we have NaN so we need to do some mvr

In [21]:
df.dtypes

Dataline              int64
Play                 object
PlayerLinenumber    float64
ActSceneLine         object
Player               object
PlayerLine           object
dtype: object

In [22]:
df.loc[df['PlayerLinenumber'].isnull()]

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,NaN,NaN,NaN,ACT I
1,2,Henry IV,NaN,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,NaN,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."

In [26]:
df['PlayerLinenumber'].fillna(0, inplace=True)

In [27]:
df.loc[df['ActSceneLine'].isnull()]

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,0.0,NaN,NaN,ACT I
1,2,Henry IV,0.0,NaN,NaN,SCENE I. London. The palace.
2,3,Henry IV,0.0,NaN,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
111,112,Henry IV,10.0,NaN,WESTMORELAND,Exeunt
112,113,Henry IV,10.0,NaN,WESTMORELAND,SCENE II. London. An apartment of the Prince's.
113,114,Henry IV,10.0,NaN,WESTMORELAND,Enter the PRINCE OF WALES and FALSTAFF
214,215,Henry IV,33.0,NaN,FALSTAFF,Enter POINS
264,265,Henry IV,52.0,NaN,PRINCE HENRY,Exit Falstaff
299,300,Henry IV,61.0,NaN,POINS,Exit Poins
323,324,Henry IV,62.0,NaN,PRINCE HENRY,Exit
324,325,Henry IV,62.0,NaN,PRINCE HENRY,SCENE III. London. The palace.
325,326,Henry IV,62.0,NaN,PRINCE HENRY,"Enter the KING, NORTHUMBERLAND, WORCESTER, HOT..."
347,348,Henry IV,4.0,NaN,KING HENRY IV,Exit Worcester
349,350,Henry IV,4.0,NaN,KING HENRY IV,To North
454,455,Henry IV,10.0,NaN,KING HENRY IV,"Exeunt King Henry, Blunt, and train"
461,462,Henry IV,12.0,NaN,NORTHUMBERLAND,Re-enter WORCESTER
604,605,Henry IV,42.0,NaN,EARL OF WORCESTER,To Northumberland
644,645,Henry IV,54.0,NaN,HOTSPUR,Exeunt
645,646,Henry IV,54.0,NaN,HOTSPUR,ACT II
646,647,Henry IV,54.0,NaN,HOTSPUR,SCENE I. Rochester. An inn yard.
647,648,Henry IV,54.0,NaN,HOTSPUR,Enter a Carrier with a lantern in his hand
655,656,Henry IV,3.0,NaN,First Carrier,Enter another Carrier
678,679,Henry IV,11.0,NaN,First Carrier,Enter GADSHILL
692,693,Henry IV,19.0,NaN,Second Carrier,Exeunt carriers
699,700,Henry IV,22.0,NaN,GADSHILL,Enter Chamberlain
744,745,Henry IV,32.0,NaN,GADSHILL,Exeunt
745,746,Henry IV,32.0,NaN,GADSHILL,"SCENE II. The highway, near Gadshill."
746,747,Henry IV,32.0,NaN,GADSHILL,Enter PRINCE HENRY and POINS
750,751,Henry IV,2.0,NaN,PRINCE HENRY,Enter FALSTAFF
775,776,Henry IV,7.0,NaN,FALSTAFF,They whistle
...,...,...,...,...,...,...
110533,110534,A Winters Tale,179.0,NaN,CAMILLO,FLORIZEL and AUTOLYCUS exchange garments
110549,110550,A Winters Tale,183.0,NaN,CAMILLO,Giving it to PERDITA
110563,110564,A Winters Tale,188.0,NaN,CAMILLO,"Exeunt FLORIZEL, PERDITA, and CAMILLO"
110578,110579,A Winters Tale,189.0,NaN,AUTOLYCUS,Re-enter Clown and Shepherd
110609,110610,A Winters Tale,201.0,NaN,AUTOLYCUS,Takes off his false beard
110723,110724,A Winters Tale,239.0,NaN,Shepherd,Exeunt Shepherd and Clown
110736,110737,A Winters Tale,240.0,NaN,AUTOLYCUS,Exit
110737,110738,A Winters Tale,240.0,NaN,AUTOLYCUS,ACT V
110738,110739,A Winters Tale,240.0,NaN,AUTOLYCUS,SCENE I. A room in LEONTES' palace.
110739,110740,A Winters Tale,240.0,NaN,AUTOLYCUS,"Enter LEONTES, CLEOMENES, DION, PAULINA, and S..."
110793,110794,A Winters Tale,8.0,NaN,PAULINA,To LEONTES
110847,110848,A Winters Tale,24.0,NaN,PAULINA,Enter a Gentleman
110885,110886,A Winters Tale,34.0,NaN,LEONTES,Exeunt CLEOMENES and others
110896,110897,A Winters Tale,36.0,NaN,LEONTES,"Re-enter CLEOMENES and others, with FLORIZEL a..."
110957,110958,A Winters Tale,42.0,NaN,LEONTES,Enter a Lord
111020,111021,A Winters Tale,59.0,NaN,LEONTES,To FLORIZEL
111027,111028,A Winters Tale,59.0,NaN,LEONTES,Exeunt
111028,111029,A Winters Tale,59.0,NaN,LEONTES,SCENE II. Before LEONTES' palace.
111029,111030,A Winters Tale,59.0,NaN,LEONTES,Enter AUTOLYCUS and a Gentleman
111048,111049,A Winters Tale,4.0,NaN,First Gentleman,Enter another Gentleman
111055,111056,A Winters Tale,5.0,NaN,Second Gentleman,Enter a third Gentleman
111143,111144,A Winters Tale,18.0,NaN,First Gentleman,Exeunt Gentlemen
111155,111156,A Winters Tale,19.0,NaN,AUTOLYCUS,Enter Shepherd and Clown
111206,111207,A Winters Tale,38.0,NaN,Clown,Exeunt
111207,111208,A Winters Tale,38.0,NaN,Clown,SCENE III. A chapel in PAULINA'S house.
111208,111209,A Winters Tale,38.0,NaN,Clown,"Enter LEONTES, POLIXENES, FLORIZEL, PERDITA, C..."
111232,111233,A Winters Tale,4.0,NaN,PAULINA,"PAULINA draws a curtain, and discovers HERMION..."
111330,111331,A Winters Tale,30.0,NaN,PAULINA,Music
111336,111337,A Winters Tale,30.0,NaN,PAULINA,HERMIONE comes down
111395,111396,A Winters Tale,38.0,NaN,LEONTES,Exeunt

In [28]:
df['ActSceneLine'].fillna("trans", inplace=True)

In [29]:
df.loc[df['ActSceneLine'].isnull()]

Empty DataFrame
Columns: [Dataline, Play, PlayerLinenumber, ActSceneLine, Player, PlayerLine]
Index: []

In [30]:
df.loc[df['Player'].isnull()]

,Dataline,Play,PlayerLinenumber,ActSceneLine,Player,PlayerLine
0,1,Henry IV,0.0,trans,NaN,ACT I
1,2,Henry IV,0.0,trans,NaN,SCENE I. London. The palace.
2,3,Henry IV,0.0,trans,NaN,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
2015,2016,Henry IV,10.0,trans,NaN,Eastcheap. The Boar's-Head Tavern.
2016,2017,Henry IV,10.0,trans,NaN,Enter FALSTAFF and BARDOLPH
29459,29460,Cymbeline,7.0,2.2.55,NaN,An ante-chamber adjoining Imogen's apartments.
29460,29461,Cymbeline,7.0,trans,NaN,Enter CLOTEN and Lords

In [31]:
df['Player'].fillna("OTHER", inplace=True)

In [32]:
df.loc[df['Player'].isnull()]

Empty DataFrame
Columns: [Dataline, Play, PlayerLinenumber, ActSceneLine, Player, PlayerLine]
Index: []

In [33]:
df.loc[df['PlayerLine'].isnull()]

Empty DataFrame
Columns: [Dataline, Play, PlayerLinenumber, ActSceneLine, Player, PlayerLine]
Index: []

In [36]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Dataline, Play, PlayerLinenumber, ActSceneLine, Player, PlayerLine]
Index: []

## We can see we have filled all the missing values

In [47]:
df.rename(index=str, columns={"PlayerLinenumber": "LineNumber", "PlayerLine": "Line"}, inplace=True)

In [48]:
df.drop(columns=["Dataline"])

,Play,LineNumber,ActSceneLine,Player,Line
0,Henry IV,0.0,trans,OTHER,ACT I
1,Henry IV,0.0,trans,OTHER,SCENE I. London. The palace.
2,Henry IV,0.0,trans,OTHER,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ..."
3,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,"
4,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,"
5,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils
6,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.
7,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil
8,Henry IV,1.0,1.1.6,KING HENRY IV,Shall daub her lips with her own children's bl...
9,Henry IV,1.0,1.1.7,KING HENRY IV,"Nor more shall trenching war channel her fields,"
10,Henry IV,1.0,1.1.8,KING HENRY IV,Nor bruise her flowerets with the armed hoofs
11,Henry IV,1.0,1.1.9,KING HENRY IV,"Of hostile paces: those opposed eyes,"
12,Henry IV,1.0,1.1.10,KING HENRY IV,"Which, like the meteors of a troubled heaven,"
13,Henry IV,1.0,1.1.11,KING HENRY IV,"All of one nature, of one substance bred,"
14,Henry IV,1.0,1.1.12,KING HENRY IV,Did lately meet in the intestine shock
15,Henry IV,1.0,1.1.13,KING HENRY IV,And furious close of civil butchery
16,Henry IV,1.0,1.1.14,KING HENRY IV,"Shall now, in mutual well-beseeming ranks,"
17,Henry IV,1.0,1.1.15,KING HENRY IV,March all one way and be no more opposed
18,Henry IV,1.0,1.1.16,KING HENRY IV,"Against acquaintance, kindred and allies:"
19,Henry IV,1.0,1.1.17,KING HENRY IV,"The edge of war, like an ill-sheathed knife,"
20,Henry IV,1.0,1.1.18,KING HENRY IV,"No more shall cut his master. Therefore, friends,"
21,Henry IV,1.0,1.1.19,KING HENRY IV,"As far as to the sepulchre of Christ,"
22,Henry IV,1.0,1.1.20,KING HENRY IV,"Whose soldier now, under whose blessed cross"
23,Henry IV,1.0,1.1.21,KING HENRY IV,"We are impressed and engaged to fight,"
24,Henry IV,1.0,1.1.22,KING HENRY IV,"Forthwith a power of English shall we levy,"
25,Henry IV,1.0,1.1.23,KING HENRY IV,Whose arms were moulded in their mothers' womb
26,Henry IV,1.0,1.1.24,KING HENRY IV,To chase these pagans in those holy fields
27,Henry IV,1.0,1.1.25,KING HENRY IV,Over whose acres walk'd those blessed feet
28,Henry IV,1.0,1.1.26,KING HENRY IV,Which fourteen hundred years ago were nail'd
29,Henry IV,1.0,1.1.27,KING HENRY IV,For our advantage on the bitter cross.
...,...,...,...,...,...
111366,A Winters Tale,37.0,5.3.155,PAULINA,"There's time enough for that,"
111367,A Winters Tale,37.0,5.3.156,PAULINA,Lest they desire upon this push to trouble
111368,A Winters Tale,37.0,5.3.157,PAULINA,"Your joys with like relation. Go together,"
111369,A Winters Tale,37.0,5.3.158,PAULINA,"You precious winners all, your exultation"
111370,A Winters Tale,37.0,5.3.159,PAULINA,"Partake to every one. I, an old turtle,"
111371,A Winters Tale,37.0,5.3.160,PAULINA,Will wing me to some wither'd bough and there
111372,A Winters Tale,37.0,5.3.161,PAULINA,"My mate, that's never to be found again,"
111373,A Winters Tale,37.0,5.3.162,PAULINA,Lament till I am lost.
111374,A Winters Tale,38.0,5.3.163,LEONTES,"O, peace, Paulina!"
111375,A Winters Tale,38.0,5.3.164,LEONTES,"Thou shouldst a husband take by my consent,"
111376,A Winters Tale,38.0,5.3.165,LEONTES,"As I by thine a wife: this is a match,"
111377,A Winters Tale,38.0,5.3.166,LEONTES,"And made between's by vows. Thou hast found mine,"
111378,A Winters Tale,38.0,5.3.167,LEONTES,"But how, is to be question'd, for I saw her,"
111379,A Winters Tale,38.0,5.3.168,LEONTES,"As I thought, dead, and have in vain said many"
111380,A Winters Tale,38.0,5.3.169,LEONTES,A prayer upon her grave. I'll not seek far--
111381,A Winters Tale,38.0,5.3.170,LEONTES,"For him, I partly know his mind--to find thee"
111382,A Winters Tale,38.0,5.3.171,LEONTES,"An honourable husband. Come, Camillo,"
111383,A Winters Tale,38.0,5.3.172,LEONTES,"And take her by the hand, whose worth and honesty"
111384,A Winters Tale,38.0,5.3.173,LEONTES,Is richly noted and here justified
111385,A Winters Tale,38.0,5.3.174,LEONTES,"By us, a pair of kings. Let's from this place."
111386,A Winters Tale,38.0,5.3.175,LEONTES,"What! look upon my brother: both your pardons,"
111387,A Winters Tale,38.0,5.3.176,LEONTES,That e'er I put between your holy looks
111388,A Winters Tale,38.0,5.3.177,LEONTES,"My ill suspicion. This is your son-in-law,"
111389,A Winters Tale,38.0,5.3.178,LEONTES,"And son unto the king, who, heavens directing,"
111390,A Winters Tale,38.0,5.3.179,LEONTES,"Is troth-plight to your daughter. Good Paulina,"
111391,A Winters Tale,38.0,5.3.180,LEONTES,"Lead us from hence, where we may leisurely"
111392,A Winters Tale,38.0,5.3.181,LEONTES,Each one demand an answer to his part
111393,A Winters Tale,38.0,5.3.182,LEONTES,Perform'd in this wide gap of time since first
111394,A Winters Tale,38.0,5.3.183,LEONTES,We were dissever'd: hastily lead away.
111395,A Winters Tale,38.0,trans,LEONTES,Exeunt

In [51]:
df.Player.nunique()

935

In [52]:
df['Player'] = df['Player'].astype(str)

In [53]:
df['LineLength'] = df.apply(lambda row : len(row.Line), axis=1)

In [71]:
df.head()

,Dataline,Play,LineNumber,ActSceneLine,Player,Line,LineLength
0,1,Henry IV,0.0,trans,OTHER,ACT I,5
1,2,Henry IV,0.0,trans,OTHER,SCENE I. London. The palace.,28
2,3,Henry IV,0.0,trans,OTHER,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ...",96
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",38
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",42

In [77]:
import collections
df['MostCommonLetter'] = df.apply(lambda row : ord(collections.Counter(row.Line).most_common(1)[0][0]), axis=1)

In [80]:
df.drop(columns=['rsf'])

,Dataline,Play,LineNumber,ActSceneLine,Player,Line,LineLength,MostCommonLetter
0,1,Henry IV,0.0,trans,OTHER,ACT I,5,65
1,2,Henry IV,0.0,trans,OTHER,SCENE I. London. The palace.,28,32
2,3,Henry IV,0.0,trans,OTHER,"Enter KING HENRY, LORD JOHN OF LANCASTER, the ...",96,32
3,4,Henry IV,1.0,1.1.1,KING HENRY IV,"So shaken as we are, so wan with care,",38,32
4,5,Henry IV,1.0,1.1.2,KING HENRY IV,"Find we a time for frighted peace to pant,",42,32
5,6,Henry IV,1.0,1.1.3,KING HENRY IV,And breathe short-winded accents of new broils,46,32
6,7,Henry IV,1.0,1.1.4,KING HENRY IV,To be commenced in strands afar remote.,39,32
7,8,Henry IV,1.0,1.1.5,KING HENRY IV,No more the thirsty entrance of this soil,41,32
8,9,Henry IV,1.0,1.1.6,KING HENRY IV,Shall daub her lips with her own children's bl...,50,32
9,10,Henry IV,1.0,1.1.7,KING HENRY IV,"Nor more shall trenching war channel her fields,",48,32
10,11,Henry IV,1.0,1.1.8,KING HENRY IV,Nor bruise her flowerets with the armed hoofs,45,32
11,12,Henry IV,1.0,1.1.9,KING HENRY IV,"Of hostile paces: those opposed eyes,",37,101
12,13,Henry IV,1.0,1.1.10,KING HENRY IV,"Which, like the meteors of a troubled heaven,",45,32
13,14,Henry IV,1.0,1.1.11,KING HENRY IV,"All of one nature, of one substance bred,",41,32
14,15,Henry IV,1.0,1.1.12,KING HENRY IV,Did lately meet in the intestine shock,38,32
15,16,Henry IV,1.0,1.1.13,KING HENRY IV,And furious close of civil butchery,35,32
16,17,Henry IV,1.0,1.1.14,KING HENRY IV,"Shall now, in mutual well-beseeming ranks,",42,108
17,18,Henry IV,1.0,1.1.15,KING HENRY IV,March all one way and be no more opposed,40,32
18,19,Henry IV,1.0,1.1.16,KING HENRY IV,"Against acquaintance, kindred and allies:",41,97
19,20,Henry IV,1.0,1.1.17,KING HENRY IV,"The edge of war, like an ill-sheathed knife,",44,101
20,21,Henry IV,1.0,1.1.18,KING HENRY IV,"No more shall cut his master. Therefore, friends,",49,32
21,22,Henry IV,1.0,1.1.19,KING HENRY IV,"As far as to the sepulchre of Christ,",37,32
22,23,Henry IV,1.0,1.1.20,KING HENRY IV,"Whose soldier now, under whose blessed cross",44,115
23,24,Henry IV,1.0,1.1.21,KING HENRY IV,"We are impressed and engaged to fight,",38,101
24,25,Henry IV,1.0,1.1.22,KING HENRY IV,"Forthwith a power of English shall we levy,",43,32
25,26,Henry IV,1.0,1.1.23,KING HENRY IV,Whose arms were moulded in their mothers' womb,46,32
26,27,Henry IV,1.0,1.1.24,KING HENRY IV,To chase these pagans in those holy fields,42,32
27,28,Henry IV,1.0,1.1.25,KING HENRY IV,Over whose acres walk'd those blessed feet,42,101
28,29,Henry IV,1.0,1.1.26,KING HENRY IV,Which fourteen hundred years ago were nail'd,44,32
29,30,Henry IV,1.0,1.1.27,KING HENRY IV,For our advantage on the bitter cross.,38,32
...,...,...,...,...,...,...,...,...
111366,111367,A Winters Tale,37.0,5.3.155,PAULINA,"There's time enough for that,",29,101
111367,111368,A Winters Tale,37.0,5.3.156,PAULINA,Lest they desire upon this push to trouble,42,32
111368,111369,A Winters Tale,37.0,5.3.157,PAULINA,"Your joys with like relation. Go together,",42,32
111369,111370,A Winters Tale,37.0,5.3.158,PAULINA,"You precious winners all, your exultation",41,32
111370,111371,A Winters Tale,37.0,5.3.159,PAULINA,"Partake to every one. I, an old turtle,",39,32
111371,111372,A Winters Tale,37.0,5.3.160,PAULINA,Will wing me to some wither'd bough and there,45,32
111372,111373,A Winters Tale,37.0,5.3.161,PAULINA,"My mate, that's never to be found again,",40,32
111373,111374,A Winters Tale,37.0,5.3.162,PAULINA,Lament till I am lost.,22,32
111374,111375,A Winters Tale,38.0,5.3.163,LEONTES,"O, peace, Paulina!",18,97
111375,111376,A Winters Tale,38.0,5.3.164,LEONTES,"Thou shouldst a husband take by my consent,",43,32
111376,111377,A Winters Tale,38.0,5.3.165,LEONTES,"As I by thine a wife: this is a match,",38,32
111377,111378,A Winters Tale,38.0,5.3.166,LEONTES,"And made between's by vows. Thou hast found mine,",49,32
111378,111379,A Winters Tale,38.0,5.3.167,LEONTES,"But how, is to be question'd, for I saw her,",44,32
111379,111380,A Winters Tale,38.0,5.3.168,LEONTES,"As I thought, dead, and have in vain said many",46,32
111380,111381,A Winters Tale,38.0,5.3.169,LEONTES,A prayer upon her grave. I'll not seek far--,44,32
111381,111382,A Winters Tale,38.0,5.3.170,LEONTES,"For him, I partly know his mind--to find thee",45,32
111382,111383,A Winters Tale,38.0,5.3.171,LEONTES,"An honourable husband. Come, Camillo,",37,32
111383,111384,A Winters Tale,38.0,5.3.172,LEONTES,"And take her by the hand, whose worth and honesty",49,32
111384,111385,A Winters Tale,38.0,5.3.173,LEONTES,Is richly noted and here justified,34,32
111385,111386,A Winters Tale,38.0,5.3.174,LEONTES,"By us, a pair of kings. Let's from this place.",46,32
111386,111387,A Winters Tale,38.0,5.3.175,LEONTES,"What! look upon my brother: both your pardons,",46,32
111387,111388,A Winters Tale,38.0,5.3.176,LEONTES,That e'er I put between your holy looks,39,32
111388,111389,A Winters Tale,38.0,5.3.177,LEONTES,"My ill suspicion. This is your son-in-law,",42,32
111389,111390,A Winters Tale,38.0,5.3.178,LEONTES,"And son unto the king, who, heavens directing,",46,32
111390,111391,A Winters Tale,38.0,5.3.179,LEONTES,"Is troth-plight to your daughter. Good Paulina,",47,32
111391,111392,A Winters Tale,38.0,5.3.180,LEONTES,"Lead us from hence, where we may leisurely",42,101
111392,111393,A Winters Tale,38.0,5.3.181,LEONTES,Each one demand an answer to his part,37,32
111393,111394,A Winters Tale,38.0,5.3.182,LEONTES,Perform'd in this wide gap of time since first,46,32
111394,111395,A Winters Tale,38.0,5.3.183,LEONTES,We were dissever'd: hastily lead away.,38,101
111395,111396,A Winters Tale,38.0,trans,LEONTES,Exeunt,6,69

In [40]:
from sklearn.model_selection import train_test_split